bar:
  height: 25
  location: top
  font: Cozette:style=bold:size=10
  layer: top
  foreground: a89984ff
  background: 282828ff
  left:
    - river:
        anchors:
          - base: &river_base
              left-margin: 10
              right-margin: 10
              conditions:
                id == 1: {string: {text: 一}}
                id == 2: {string: {text: 二}}
                id == 3: {string: {text: 三}}
                id == 4: {string: {text: 四}}
                id == 5: {string: {text: 五}}
                id == 6: {string: {text: 六}}
                id == 7: {string: {text: 七}}
                id == 8: {string: {text: 八}}
                id == 9: {string: {text: 九}}
        content:
          map:
            default:
              map:
                <<: *river_base
                on-click:
                  left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
                  right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
            conditions:
              state == focused:
                map:
                  <<: *river_base
                  deco: {stack: [{background: {color: 504945ff}}]}
              state == invisible && ~occupied && id > 9 && id != 10: {empty: {}}
    - foreign-toplevel:
        content:
          map:
            margin: 20
            default: {empty: {}}
            conditions:
              activated: {string: {text: "{app-id}", foreground: a89984ff}}
  right:
    - pulse:
        content:
          map:
            margin: 20
            default: {empty: {}}
            conditions:
              sink_online: {string: {text: "{sink_percent}%", foreground: a89984ff}}
    - clock:
        content:
        - string: {text: "{date} {time}",right-margin: 14, foreground: a89984ff}
